/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import clases.Ponderacion;

/**
 *
 * @author pablo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_01 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_02 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_03 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_04 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_05 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Promedio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Introducir 5 calificaciones y mostrar el promedio.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 21, -1, -1));

        txt_01.setText("0");
        jPanel1.add(txt_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, -1));

        jLabel2.setText("Promedio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        txt_02.setText("0");
        jPanel1.add(txt_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, -1));

        jLabel3.setText("Calificación 2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txt_03.setText("0");
        jPanel1.add(txt_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, -1));

        jLabel4.setText("Calificación 3:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txt_04.setText("0");
        jPanel1.add(txt_04, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 60, -1));

        jLabel5.setText("Calificación 4:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txt_05.setText("0");
        jPanel1.add(txt_05, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 60, -1));

        jLabel6.setText("Calificación 5:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txt_Promedio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_Promedio.setText("0");
        jPanel1.add(txt_Promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 60, -1));

        jLabel8.setText("Calificación 1:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        btn_Calcular.setText("Calcular");
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        
        double c1, c2, c3, c4, c5;
        
        c1 = Double.valueOf(txt_01.getText());
        c2 = Double.valueOf(txt_02.getText());
        c3 = Double.valueOf(txt_03.getText());
        c4 = Double.valueOf(txt_04.getText());
        c5 = Double.valueOf(txt_05.getText());
        
        Ponderacion p = new Ponderacion(c1, c2, c3, c4, c5);
        
        txt_Promedio.setText(String.valueOf(p.getPromedio()));
        
    }//GEN-LAST:event_btn_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_01;
    private javax.swing.JTextField txt_02;
    private javax.swing.JTextField txt_03;
    private javax.swing.JTextField txt_04;
    private javax.swing.JTextField txt_05;
    private javax.swing.JLabel txt_Promedio;
    // End of variables declaration//GEN-END:variables
}
